// Project data — original placeholder content, not copied from any real product
const PROJECTS = {
  robotisation: [
    {
      id: 'RPA-001',
      title: 'Project Forecast Automation',
      category: 'RPA',
      dept: 'PMO',
      tag: 'Operations',
      desc: 'Auto-aggregates project forecast spreadsheets from 14 sites into a single SAP-ready submission.',
      long: 'A scheduled UiPath bot collects the weekly forecast Excel templates from a shared location, validates them against a central project register, normalizes line-item codes, and posts a consolidated CSV to the SAP staging area. Replaces ~6 hours of manual copy-paste each Monday.',
      status: 'Live',
      hours: '24h',
      stack: ['UiPath', 'Excel', 'SAP'],
      bullets: [
        'Picks up 14 templates on a schedule from network share',
        'Validates project codes against central register',
        'Posts consolidated CSV to SAP staging',
        'Sends a digest to the PMO team channel',
      ],
      owner: 'M. Novakova',
      gradient: 'linear-gradient(135deg, #300091, #6f79bd)',
      accent: '#300091',
      Icon: 'Robot',
    },
    {
      id: 'RPA-002',
      title: 'Cost Center Capitalization in SAP',
      category: 'RPA',
      dept: 'Finance',
      tag: 'SAP',
      desc: 'Books CapEx capitalization journals into SAP from a curated approval queue, end-to-end.',
      long: 'A bot reads approved capitalization requests from a Power Apps queue, looks up the matching cost centers, validates the journal lines, and posts the bookings into SAP. Adds an audit trail with screenshots into a Confluence run log.',
      status: 'Live',
      hours: '48h',
      stack: ['UiPath', 'SAP', 'Power Apps'],
      bullets: [
        'Pulls approved requests from a curated queue',
        'Resolves cost center / WBS mappings',
        'Posts journal entries directly in SAP',
        'Logs an audit trail with screenshots',
      ],
      owner: 'P. Horak',
      gradient: 'linear-gradient(135deg, #1f005c, #41b6e6)',
      accent: '#300091',
      Icon: 'Money',
    },
    {
      id: 'RPA-003',
      title: 'Public Registry Web Scraper',
      category: 'RPA',
      dept: 'Network',
      tag: 'Government',
      desc: 'Scrapes parcel and ownership data from the public cadastre portal for network deployment planning.',
      long: 'For each new deployment polygon, the bot queries the public registry, downloads ownership and parcel attributes, normalizes them into a standard schema, and writes them back to the deployment planning database. Runs nightly with built-in rate-limiting.',
      status: 'Live',
      hours: '60h',
      stack: ['UiPath', 'GitLab', 'Dataverse'],
      bullets: [
        'Iterates new deployment polygons each night',
        'Throttles requests to respect portal limits',
        'Normalizes parcel + ownership data',
        'Writes to deployment planning DB',
      ],
      owner: 'J. Vesely',
      gradient: 'linear-gradient(135deg, #300091, #1f005c)',
      accent: '#300091',
      Icon: 'Globe',
    },
    {
      id: 'RPA-004',
      title: 'Sales — Mobile Service Re-keying',
      category: 'RPA',
      dept: 'Sales',
      tag: 'Sales',
      desc: 'Transcribes mobile service orders from CRM exports into the legacy provisioning portal.',
      long: 'Bot picks up daily CRM exports, normalizes service codes, logs into the legacy provisioning portal and creates the orders one by one. Tracks failures into an exception queue with screenshots so the operator can fix and re-run.',
      status: 'Live',
      hours: '32h',
      stack: ['UiPath', 'Excel'],
      bullets: [
        'Reads daily CRM service order exports',
        'Maps to legacy portal field schema',
        'Provisions orders end-to-end',
        'Quarantines exceptions with screenshots',
      ],
      owner: 'L. Dvorak',
      gradient: 'linear-gradient(135deg, #1f005c, #6f79bd)',
      accent: '#300091',
      Icon: 'Briefcase',
    },
  ],
  digitalisation: [
    {
      id: 'PA-101',
      title: 'Grant Project Management',
      category: 'Power App',
      dept: 'Finance',
      tag: 'Operations',
      desc: 'Replaced shared Excel trackers with a structured app for grant projects with role-based approvals.',
      long: 'Project leads register grant projects through a guided form. Approvals route via Power Automate to controllers, then to the head of finance. The app keeps a single source of truth for status, deliverables and milestone payments — replacing ~4 spreadsheets that previously drifted out of sync.',
      status: 'Live',
      hours: '40h',
      stack: ['Power Apps', 'Power Automate', 'Dataverse'],
      bullets: [
        'Guided multi-step grant intake form',
        'Role-based approval routing',
        'Milestone & payment tracking',
        'Confluence-published status digest',
      ],
      owner: 'A. Cerna',
      gradient: 'linear-gradient(135deg, #41b6e6, #300091)',
      accent: '#41b6e6',
      Icon: 'Form',
    },
    {
      id: 'PA-102',
      title: 'FTTH Installation Card Digitization',
      category: 'Power App',
      dept: 'Network',
      tag: 'Operations',
      desc: 'Field crews submit installation cards on tablets — replacing scanned paper forms.',
      long: 'Field crews capture photos, signatures and metering data through a Power App on tablets. Submitted cards are automatically linked to the corresponding work order, and a Power Automate flow notifies the back office and uploads the package to the deployment archive.',
      status: 'Live',
      hours: '70h',
      stack: ['Power Apps', 'Power Automate', 'SharePoint'],
      bullets: [
        'Tablet-friendly capture for field crews',
        'Photo & signature attachment',
        'Auto-link to work order',
        'Archive upload + back-office notification',
      ],
      owner: 'T. Kral',
      gradient: 'linear-gradient(135deg, #41b6e6, #99d6ea)',
      accent: '#41b6e6',
      Icon: 'Clipboard',
    },
    {
      id: 'PA-103',
      title: 'Construction Deployment Tracker',
      category: 'Power App',
      dept: 'Network',
      tag: 'Operations',
      desc: 'Live progress tracking for construction crews with photo-based proof and route playback.',
      long: 'Foremen log daily progress against the deployment plan: meters built, equipment installed, blockers. The app rolls up to a Power BI dashboard so the deployment manager can see today\'s plan vs actual at a glance.',
      status: 'Pilot',
      hours: '36h',
      stack: ['Power Apps', 'Power BI'],
      bullets: [
        'Daily progress capture',
        'Photo proof per segment',
        'Plan vs actual rollup',
        'Blocker queue for back office',
      ],
      owner: 'R. Benes',
      gradient: 'linear-gradient(135deg, #6f79bd, #41b6e6)',
      accent: '#41b6e6',
      Icon: 'Network',
    },
    {
      id: 'PA-104',
      title: 'Network Damage Incident Report',
      category: 'Power App',
      dept: 'Operations',
      tag: 'Operations',
      desc: 'Structured damage incident form with auto-routing to liability and field repair teams.',
      long: 'Anyone in the field can file a damage report with photos and GPS coordinates. The app auto-routes to liability and field repair, opens a tracking record, and triggers a follow-up SLA timer with reminders.',
      status: 'Live',
      hours: '20h',
      stack: ['Power Apps', 'Power Automate'],
      bullets: [
        'Photo + GPS damage capture',
        'Auto-routing to liability + repair',
        'SLA timer with reminders',
        'Closeout audit log',
      ],
      owner: 'V. Mraz',
      gradient: 'linear-gradient(135deg, #99d6ea, #6f79bd)',
      accent: '#41b6e6',
      Icon: 'Doc',
    },
  ],
  reporting: [
    {
      id: 'RPT-201',
      title: 'Network Deployment Report',
      category: 'Power BI',
      dept: 'Network',
      tag: 'Operations',
      desc: 'Live deployment dashboard replacing weekly Excel rollups across 6 regions.',
      long: 'Pulls construction, design and provisioning data into a single semantic model. Region leads see plan vs actual, blockers, and forecast confidence — refreshed every 30 minutes. Replaces a weekly Excel deck assembled by hand.',
      status: 'Live',
      hours: '50h',
      stack: ['Power BI', 'Dataverse', 'Azure'],
      bullets: [
        'Unified semantic model across 3 source systems',
        'Plan vs actual at site & region level',
        'Forecast confidence indicator',
        '30-minute incremental refresh',
      ],
      owner: 'I. Pospichal',
      gradient: 'linear-gradient(135deg, #f12e49, #1f005c)',
      accent: '#f12e49',
      Icon: 'Chart',
    },
    {
      id: 'RPT-202',
      title: 'Group Project Portfolio',
      category: 'Power BI',
      dept: 'PMO',
      tag: 'Operations',
      desc: 'Exec-level view of every active initiative — status, RAG, capex burn and milestone health.',
      long: 'Connects the PMO Power App to a curated portfolio dashboard. Each project rolls up by program, stream and sponsor with drilldown into milestone health, capex burn, and resourcing pressure.',
      status: 'Live',
      hours: '28h',
      stack: ['Power BI', 'Power Apps', 'Dataverse'],
      bullets: [
        'Program / stream / sponsor rollups',
        'RAG status with drilldown',
        'Capex burn tracking',
        'Resourcing heatmap',
      ],
      owner: 'A. Cerna',
      gradient: 'linear-gradient(135deg, #f12e49, #6f79bd)',
      accent: '#f12e49',
      Icon: 'Layers',
    },
    {
      id: 'RPT-203',
      title: 'Vendor Timesheet Report',
      category: 'Power BI',
      dept: 'Finance',
      tag: 'Finance',
      desc: 'Replaces Excel pivots with a controlled vendor timesheet model and exception queue.',
      long: 'Vendor timesheets land in a curated bronze layer, are reconciled against POs and approval workflows, and surface in a Power BI report with an exception queue for finance to clear before month-end close.',
      status: 'Live',
      hours: '30h',
      stack: ['Power BI', 'Azure', 'Dataverse'],
      bullets: [
        'PO reconciliation built in',
        'Exception queue for clearing',
        'Month-end close cutover view',
        'Vendor self-service drilldown',
      ],
      owner: 'P. Horak',
      gradient: 'linear-gradient(135deg, #1f005c, #f12e49)',
      accent: '#f12e49',
      Icon: 'Database',
    },
    {
      id: 'RPT-204',
      title: 'Change Management Reporting',
      category: 'Confluence',
      dept: 'PMO',
      tag: 'Operations',
      desc: 'Auto-published change request digest with weekly cadence and stakeholder routing.',
      long: 'A scheduled flow reads the change request register, summarizes movement since last week, renders a Confluence page per program, and emails stakeholders a curated digest. Replaces a manually compiled change report.',
      status: 'Live',
      hours: '18h',
      stack: ['Confluence', 'Power Automate'],
      bullets: [
        'Weekly auto-published digest',
        'Per-program Confluence page',
        'Stakeholder-routed email summary',
        'Searchable change archive',
      ],
      owner: 'M. Novakova',
      gradient: 'linear-gradient(135deg, #6f79bd, #f12e49)',
      accent: '#f12e49',
      Icon: 'Doc',
    },
  ],
};

window.PROJECTS = PROJECTS;
