// Project data — original placeholder content, bilingual EN + CZ
const PROJECTS = {
  robotisation: [
    {
      id: 'RPA-001',
      title: 'Project Forecast Automation',
      titleCz: 'Automatizace prognózy projektů',
      category: 'RPA',
      dept: 'PMO',
      tag: 'Operations',
      desc: 'Auto-aggregates project forecast spreadsheets from 14 sites into a single SAP-ready submission.',
      descCz: 'Automaticky slučuje prognózové tabulky projektů ze 14 lokalit do jediného podání připraveného pro SAP.',
      long: 'A scheduled UiPath bot collects the weekly forecast Excel templates from a shared location, validates them against a central project register, normalizes line-item codes, and posts a consolidated CSV to the SAP staging area. Replaces ~6 hours of manual copy-paste each Monday.',
      longCz: 'Naplánovaný UiPath robot sbírá týdenní Excel šablony prognóz ze sdíleného úložiště, ověřuje je oproti centrálnímu registru projektů, normalizuje kódy položek a odesílá konsolidovaný CSV soubor do SAP staging prostředí. Nahrazuje přibližně 6 hodin ručního kopírování každé pondělí.',
      status: 'Live',
      hours: '24h',
      stack: ['UiPath', 'Excel', 'SAP'],
      bullets: [
        'Picks up 14 templates on a schedule from network share',
        'Validates project codes against central register',
        'Posts consolidated CSV to SAP staging',
        'Sends a digest to the PMO team channel',
      ],
      bulletsCz: [
        'Stahuje 14 šablon podle plánu ze sdílené sítě',
        'Ověřuje kódy projektů oproti centrálnímu registru',
        'Odesílá konsolidovaný CSV do SAP staging prostředí',
        'Zasílá přehled do týmového kanálu PMO',
      ],
      owner: 'M. Novakova',
      gradient: 'linear-gradient(135deg, #300091, #6f79bd)',
      accent: '#300091',
      Icon: 'Robot',
    },
    {
      id: 'RPA-002',
      title: 'Cost Center Capitalization in SAP',
      titleCz: 'Kapitalizace nákladových středisek v SAP',
      category: 'RPA',
      dept: 'Finance',
      tag: 'SAP',
      desc: 'Books CapEx capitalization journals into SAP from a curated approval queue, end-to-end.',
      descCz: 'Zaúčtovává deníky kapitalizace CapEx do SAP z kontrolované fronty schválení, od začátku do konce.',
      long: 'A bot reads approved capitalization requests from a Power Apps queue, looks up the matching cost centers, validates the journal lines, and posts the bookings into SAP. Adds an audit trail with screenshots into a Confluence run log.',
      longCz: 'Robot čte schválené žádosti o kapitalizaci z fronty Power Apps, dohledá odpovídající nákladová střediska, ověří řádky deníku a zaúčtuje záznamy v SAP. Přidává auditní stopu se snímky obrazovky do Confluence provozního logu.',
      status: 'Live',
      hours: '48h',
      stack: ['UiPath', 'SAP', 'Power Apps'],
      bullets: [
        'Pulls approved requests from a curated queue',
        'Resolves cost center / WBS mappings',
        'Posts journal entries directly in SAP',
        'Logs an audit trail with screenshots',
      ],
      bulletsCz: [
        'Stahuje schválené žádosti z kontrolované fronty',
        'Vyřešuje mapování nákladových středisek / WBS',
        'Zaúčtovává deníkové záznamy přímo v SAP',
        'Zaznamenává auditní stopu se snímky obrazovky',
      ],
      owner: 'P. Horak',
      gradient: 'linear-gradient(135deg, #1f005c, #41b6e6)',
      accent: '#300091',
      Icon: 'Money',
    },
    {
      id: 'RPA-003',
      title: 'Public Registry Web Scraper',
      titleCz: 'Webový scraper veřejného katastru',
      category: 'RPA',
      dept: 'Network',
      tag: 'Government',
      desc: 'Scrapes parcel and ownership data from the public cadastre portal for network deployment planning.',
      descCz: 'Stahuje data o parcelách a vlastnících z portálu veřejného katastru pro plánování výstavby sítě.',
      long: 'For each new deployment polygon, the bot queries the public registry, downloads ownership and parcel attributes, normalizes them into a standard schema, and writes them back to the deployment planning database. Runs nightly with built-in rate-limiting.',
      longCz: 'Pro každý nový polygon výstavby robot dotazuje veřejný registr, stahuje atributy vlastnictví a parcel, normalizuje je do standardního schématu a zapisuje zpět do databáze pro plánování výstavby. Spouští se každou noc s vestavěným omezením četnosti dotazů.',
      status: 'Live',
      hours: '60h',
      stack: ['UiPath', 'GitLab', 'Dataverse'],
      bullets: [
        'Iterates new deployment polygons each night',
        'Throttles requests to respect portal limits',
        'Normalizes parcel + ownership data',
        'Writes to deployment planning DB',
      ],
      bulletsCz: [
        'Prochází nové polygony výstavby každou noc',
        'Omezuje četnost dotazů dle limitů portálu',
        'Normalizuje data parcel a vlastnictví',
        'Zapisuje do databáze pro plánování výstavby',
      ],
      owner: 'J. Vesely',
      gradient: 'linear-gradient(135deg, #300091, #1f005c)',
      accent: '#300091',
      Icon: 'Globe',
    },
    {
      id: 'RPA-004',
      title: 'Sales — Mobile Service Re-keying',
      titleCz: 'Prodej — přepis objednávek mobilních služeb',
      category: 'RPA',
      dept: 'Sales',
      tag: 'Sales',
      desc: 'Transcribes mobile service orders from CRM exports into the legacy provisioning portal.',
      descCz: 'Přepisuje objednávky mobilních služeb z exportů CRM do starého provisioningového portálu.',
      long: 'Bot picks up daily CRM exports, normalizes service codes, logs into the legacy provisioning portal and creates the orders one by one. Tracks failures into an exception queue with screenshots so the operator can fix and re-run.',
      longCz: 'Robot zpracovává denní exporty z CRM, normalizuje kódy služeb, přihlašuje se do starého provisioningového portálu a vytváří objednávky jednu po druhé. Chyby sleduje do fronty výjimek se snímky obrazovky, aby je operátor mohl opravit a spustit znovu.',
      status: 'Live',
      hours: '32h',
      stack: ['UiPath', 'Excel'],
      bullets: [
        'Reads daily CRM service order exports',
        'Maps to legacy portal field schema',
        'Provisions orders end-to-end',
        'Quarantines exceptions with screenshots',
      ],
      bulletsCz: [
        'Čte denní exporty objednávek služeb z CRM',
        'Mapuje na schéma polí starého portálu',
        'Zpracovává objednávky od začátku do konce',
        'Karantizuje výjimky se snímky obrazovky',
      ],
      owner: 'L. Dvorak',
      gradient: 'linear-gradient(135deg, #1f005c, #6f79bd)',
      accent: '#300091',
      Icon: 'Briefcase',
    },
  ],
  digitalisation: [
    {
      id: 'PA-101',
      title: 'Grant Project Management',
      titleCz: 'Správa dotačních projektů',
      category: 'Power App',
      dept: 'Finance',
      tag: 'Operations',
      desc: 'Replaced shared Excel trackers with a structured app for grant projects with role-based approvals.',
      descCz: 'Nahradil sdílené Excel tabulky strukturovanou aplikací pro dotační projekty s rolově řízenými schváleními.',
      long: 'Project leads register grant projects through a guided form. Approvals route via Power Automate to controllers, then to the head of finance. The app keeps a single source of truth for status, deliverables and milestone payments — replacing ~4 spreadsheets that previously drifted out of sync.',
      longCz: 'Vedoucí projektů registrují dotační projekty prostřednictvím průvodce formulářem. Schválení jsou směrována přes Power Automate na controllery a poté na vedoucího financí. Aplikace udržuje jediný zdroj pravdy pro stav, výstupy a platby milníků — nahrazuje přibližně 4 tabulky, které se dříve nesynchronizovaly.',
      status: 'Live',
      hours: '40h',
      stack: ['Power Apps', 'Power Automate', 'Dataverse'],
      bullets: [
        'Guided multi-step grant intake form',
        'Role-based approval routing',
        'Milestone & payment tracking',
        'Confluence-published status digest',
      ],
      bulletsCz: [
        'Průvodce vícekrokového formuláře pro příjem dotací',
        'Rolově řízené směrování schválení',
        'Sledování milníků a plateb',
        'Přehled stavu publikovaný do Confluence',
      ],
      owner: 'A. Cerna',
      gradient: 'linear-gradient(135deg, #41b6e6, #300091)',
      accent: '#41b6e6',
      Icon: 'Form',
    },
    {
      id: 'PA-102',
      title: 'FTTH Installation Card Digitization',
      titleCz: 'Digitalizace montážních karet FTTH',
      category: 'Power App',
      dept: 'Network',
      tag: 'Operations',
      desc: 'Field crews submit installation cards on tablets — replacing scanned paper forms.',
      descCz: 'Montážní čety odevzdávají montážní karty na tabletech — nahrazuje skenované papírové formuláře.',
      long: 'Field crews capture photos, signatures and metering data through a Power App on tablets. Submitted cards are automatically linked to the corresponding work order, and a Power Automate flow notifies the back office and uploads the package to the deployment archive.',
      longCz: 'Montážní čety zachycují fotografie, podpisy a měřicí data prostřednictvím Power App na tabletech. Odevzdané karty jsou automaticky propojeny s příslušnou pracovní objednávkou a flow Power Automate upozorní back office a nahraje balíček do archivu výstavby.',
      status: 'Live',
      hours: '70h',
      stack: ['Power Apps', 'Power Automate', 'SharePoint'],
      bullets: [
        'Tablet-friendly capture for field crews',
        'Photo & signature attachment',
        'Auto-link to work order',
        'Archive upload + back-office notification',
      ],
      bulletsCz: [
        'Sběr dat přizpůsobený pro tablety montážních čet',
        'Příloha fotografie a podpisu',
        'Automatické propojení s pracovní objednávkou',
        'Nahrání do archivu + upozornění back office',
      ],
      owner: 'T. Kral',
      gradient: 'linear-gradient(135deg, #41b6e6, #99d6ea)',
      accent: '#41b6e6',
      Icon: 'Clipboard',
    },
    {
      id: 'PA-103',
      title: 'Construction Deployment Tracker',
      titleCz: 'Tracker průběhu výstavby',
      category: 'Power App',
      dept: 'Network',
      tag: 'Operations',
      desc: 'Live progress tracking for construction crews with photo-based proof and route playback.',
      descCz: 'Sledování průběhu výstavby v reálném čase s fotodokumentací a přehráváním trasy.',
      long: 'Foremen log daily progress against the deployment plan: meters built, equipment installed, blockers. The app rolls up to a Power BI dashboard so the deployment manager can see today\'s plan vs actual at a glance.',
      longCz: 'Mistři zaznamenávají denní postup oproti plánu výstavby: postavené metry, instalované vybavení, překážky. Aplikace shrnuje data do Power BI dashboardu, aby manažer výstavby viděl plán vs. skutečnost na první pohled.',
      status: 'Pilot',
      hours: '36h',
      stack: ['Power Apps', 'Power BI'],
      bullets: [
        'Daily progress capture',
        'Photo proof per segment',
        'Plan vs actual rollup',
        'Blocker queue for back office',
      ],
      bulletsCz: [
        'Denní zachycení postupu prací',
        'Fotodokumentace na segment',
        'Souhrn plán vs. skutečnost',
        'Fronta překážek pro back office',
      ],
      owner: 'R. Benes',
      gradient: 'linear-gradient(135deg, #6f79bd, #41b6e6)',
      accent: '#41b6e6',
      Icon: 'Network',
    },
    {
      id: 'PA-104',
      title: 'Network Damage Incident Report',
      titleCz: 'Hlášení poškození sítě',
      category: 'Power App',
      dept: 'Operations',
      tag: 'Operations',
      desc: 'Structured damage incident form with auto-routing to liability and field repair teams.',
      descCz: 'Strukturovaný formulář hlášení poškození s automatickým směrováním na odpovědnostní a terénní opravné týmy.',
      long: 'Anyone in the field can file a damage report with photos and GPS coordinates. The app auto-routes to liability and field repair, opens a tracking record, and triggers a follow-up SLA timer with reminders.',
      longCz: 'Kdokoli v terénu může podat hlášení o poškození s fotografiemi a GPS souřadnicemi. Aplikace automaticky směruje na odpovědnost a terénní opravu, otevírá záznam pro sledování a spouští SLA časovač s připomínkami.',
      status: 'Live',
      hours: '20h',
      stack: ['Power Apps', 'Power Automate'],
      bullets: [
        'Photo + GPS damage capture',
        'Auto-routing to liability + repair',
        'SLA timer with reminders',
        'Closeout audit log',
      ],
      bulletsCz: [
        'Sběr poškození s fotografií a GPS',
        'Automatické směrování na odpovědnost a opravu',
        'SLA časovač s připomínkami',
        'Auditní log uzavření',
      ],
      owner: 'V. Mraz',
      gradient: 'linear-gradient(135deg, #99d6ea, #6f79bd)',
      accent: '#41b6e6',
      Icon: 'Doc',
    },
  ],
  reporting: [
    {
      id: 'RPT-201',
      title: 'Network Deployment Report',
      titleCz: 'Report výstavby sítě',
      category: 'Power BI',
      dept: 'Network',
      tag: 'Operations',
      desc: 'Live deployment dashboard replacing weekly Excel rollups across 6 regions.',
      descCz: 'Živý dashboard výstavby nahrazující týdenní Excel souhrny pro 6 regionů.',
      long: 'Pulls construction, design and provisioning data into a single semantic model. Region leads see plan vs actual, blockers, and forecast confidence — refreshed every 30 minutes. Replaces a weekly Excel deck assembled by hand.',
      longCz: 'Stahuje data výstavby, návrhu a provisioningu do jediného sémantického modelu. Vedoucí regionů vidí plán vs. skutečnost, překážky a jistotu prognózy — aktualizováno každých 30 minut. Nahrazuje týdenní Excel deck sestavovaný ručně.',
      status: 'Live',
      hours: '50h',
      stack: ['Power BI', 'Dataverse', 'Azure'],
      bullets: [
        'Unified semantic model across 3 source systems',
        'Plan vs actual at site & region level',
        'Forecast confidence indicator',
        '30-minute incremental refresh',
      ],
      bulletsCz: [
        'Sjednocený sémantický model ze 3 zdrojových systémů',
        'Plán vs. skutečnost na úrovni lokality a regionu',
        'Ukazatel jistoty prognózy',
        'Přírůstkové obnovení každých 30 minut',
      ],
      owner: 'I. Pospichal',
      gradient: 'linear-gradient(135deg, #f12e49, #1f005c)',
      accent: '#f12e49',
      Icon: 'Chart',
    },
    {
      id: 'RPT-202',
      title: 'Group Project Portfolio',
      titleCz: 'Portfolio projektů skupiny',
      category: 'Power BI',
      dept: 'PMO',
      tag: 'Operations',
      desc: 'Exec-level view of every active initiative — status, RAG, capex burn and milestone health.',
      descCz: 'Přehled každé aktivní iniciativy na úrovni vedení — stav, RAG, čerpání CapEx a zdraví milníků.',
      long: 'Connects the PMO Power App to a curated portfolio dashboard. Each project rolls up by program, stream and sponsor with drilldown into milestone health, capex burn, and resourcing pressure.',
      longCz: 'Propojuje PMO Power App s kurátorským portfoliovým dashboardem. Každý projekt se seskupuje podle programu, streamu a sponzora s možností přechodu do zdraví milníků, čerpání CapEx a tlaku na zdroje.',
      status: 'Live',
      hours: '28h',
      stack: ['Power BI', 'Power Apps', 'Dataverse'],
      bullets: [
        'Program / stream / sponsor rollups',
        'RAG status with drilldown',
        'Capex burn tracking',
        'Resourcing heatmap',
      ],
      bulletsCz: [
        'Souhrny podle programu / streamu / sponzora',
        'RAG stav s možností přechodu',
        'Sledování čerpání CapEx',
        'Heatmapa zdrojů',
      ],
      owner: 'A. Cerna',
      gradient: 'linear-gradient(135deg, #f12e49, #6f79bd)',
      accent: '#f12e49',
      Icon: 'Layers',
    },
    {
      id: 'RPT-203',
      title: 'Vendor Timesheet Report',
      titleCz: 'Report výkazů práce dodavatelů',
      category: 'Power BI',
      dept: 'Finance',
      tag: 'Finance',
      desc: 'Replaces Excel pivots with a controlled vendor timesheet model and exception queue.',
      descCz: 'Nahrazuje Excel kontingenční tabulky řízeným modelem výkazů práce dodavatelů a frontou výjimek.',
      long: 'Vendor timesheets land in a curated bronze layer, are reconciled against POs and approval workflows, and surface in a Power BI report with an exception queue for finance to clear before month-end close.',
      longCz: 'Výkazy práce dodavatelů přistávají v kurátorské bronzové vrstvě, jsou odsouhlaseny oproti objednávkám a schvalovacím workflowům a zobrazují se v Power BI reportu s frontou výjimek, které musí finance vyčistit před uzávěrkou měsíce.',
      status: 'Live',
      hours: '30h',
      stack: ['Power BI', 'Azure', 'Dataverse'],
      bullets: [
        'PO reconciliation built in',
        'Exception queue for clearing',
        'Month-end close cutover view',
        'Vendor self-service drilldown',
      ],
      bulletsCz: [
        'Vestavěné odsouhlasení objednávek',
        'Fronta výjimek pro vyčištění',
        'Přehled přechodu uzávěrky měsíce',
        'Self-service přechod dodavatele',
      ],
      owner: 'P. Horak',
      gradient: 'linear-gradient(135deg, #1f005c, #f12e49)',
      accent: '#f12e49',
      Icon: 'Database',
    },
    {
      id: 'RPT-204',
      title: 'Change Management Reporting',
      titleCz: 'Reporting řízení změn',
      category: 'Confluence',
      dept: 'PMO',
      tag: 'Operations',
      desc: 'Auto-published change request digest with weekly cadence and stakeholder routing.',
      descCz: 'Automaticky publikovaný přehled žádostí o změny s týdenní kadencí a směrováním na zainteresované strany.',
      long: 'A scheduled flow reads the change request register, summarizes movement since last week, renders a Confluence page per program, and emails stakeholders a curated digest. Replaces a manually compiled change report.',
      longCz: 'Naplánovaný flow čte registr žádostí o změny, shrnuje pohyby od minulého týdne, renderuje Confluence stránku pro každý program a zasílá zainteresovaným stranám kurátorský přehled e-mailem. Nahrazuje ručně sestavovaný report změn.',
      status: 'Live',
      hours: '18h',
      stack: ['Confluence', 'Power Automate'],
      bullets: [
        'Weekly auto-published digest',
        'Per-program Confluence page',
        'Stakeholder-routed email summary',
        'Searchable change archive',
      ],
      bulletsCz: [
        'Týdně automaticky publikovaný přehled',
        'Confluence stránka pro každý program',
        'E-mailový souhrn směrovaný na zainteresované strany',
        'Prohledávatelný archiv změn',
      ],
      owner: 'M. Novakova',
      gradient: 'linear-gradient(135deg, #6f79bd, #f12e49)',
      accent: '#f12e49',
      Icon: 'Doc',
    },
  ],
};

window.PROJECTS = PROJECTS;
